import type { ReportTemplate } from './types'

export const reportTemplates: ReportTemplate[] = [
  // ─── Financial ─────────────────────────────────────────────
  {
    slug: 'profit-and-loss',
    name: 'Profit & Loss',
    description: 'Revenue minus expenses over a date range',
    category: 'financial',
    icon: 'TrendingUp',
    availableFilters: ['date_range', 'project_id', 'job_id'],
    columns: [
      { key: 'category', label: 'Category', format: 'text', sortable: true },
      { key: 'revenue', label: 'Revenue', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'expenses', label: 'Expenses', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'net', label: 'Net Profit', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },
  {
    slug: 'revenue-summary',
    name: 'Revenue Summary',
    description: 'Breakdown of all revenue by month or customer',
    category: 'financial',
    icon: 'DollarSign',
    availableFilters: ['date_range', 'customer_id', 'project_id', 'group_by'],
    columns: [
      { key: 'period', label: 'Period', format: 'text', sortable: true },
      { key: 'invoiced', label: 'Invoiced', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'collected', label: 'Collected', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'outstanding', label: 'Outstanding', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    defaultGroupBy: 'month',
    showTotals: true,
  },
  {
    slug: 'expense-report',
    name: 'Expense Report',
    description: 'All expenses grouped by category or vendor',
    category: 'financial',
    icon: 'CreditCard',
    availableFilters: ['date_range', 'project_id', 'job_id', 'group_by'],
    columns: [
      { key: 'date', label: 'Date', format: 'date', sortable: true },
      { key: 'category', label: 'Category', format: 'text', sortable: true },
      { key: 'vendor', label: 'Vendor', format: 'text', sortable: true },
      { key: 'description', label: 'Description', format: 'text' },
      { key: 'amount', label: 'Amount', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },
  {
    slug: 'aging-receivables',
    name: 'Aging Receivables',
    description: 'Outstanding invoices by age (current, 30, 60, 90+ days)',
    category: 'financial',
    icon: 'Clock',
    availableFilters: ['customer_id'],
    columns: [
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'invoice_number', label: 'Invoice #', format: 'text', sortable: true },
      { key: 'issue_date', label: 'Issue Date', format: 'date', sortable: true },
      { key: 'due_date', label: 'Due Date', format: 'date', sortable: true },
      { key: 'amount_due', label: 'Amount Due', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'age_days', label: 'Days Old', format: 'number', sortable: true, align: 'right' },
      { key: 'bucket', label: 'Aging Bucket', format: 'text', sortable: true },
    ],
    showTotals: true,
  },
  {
    slug: 'accounts-payable',
    name: 'Accounts Payable',
    description: 'Outstanding purchase orders and bills',
    category: 'financial',
    icon: 'FileText',
    availableFilters: ['date_range', 'status'],
    columns: [
      { key: 'po_number', label: 'PO #', format: 'text', sortable: true },
      { key: 'vendor', label: 'Vendor', format: 'text', sortable: true },
      { key: 'date', label: 'Date', format: 'date', sortable: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
      { key: 'total', label: 'Total', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },
  {
    slug: 'tax-summary',
    name: 'Tax Summary',
    description: 'Tax collected and owed for a period',
    category: 'financial',
    icon: 'Percent',
    availableFilters: ['date_range'],
    columns: [
      { key: 'period', label: 'Period', format: 'text', sortable: true },
      { key: 'taxable_revenue', label: 'Taxable Revenue', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'tax_collected', label: 'Tax Collected', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'tax_rate', label: 'Effective Rate', format: 'percent', align: 'right' },
    ],
    showTotals: true,
  },
  {
    slug: 'payments-received',
    name: 'Payments Received',
    description: 'All payments with method, date, and invoice reference',
    category: 'financial',
    icon: 'Banknote',
    availableFilters: ['date_range', 'customer_id'],
    columns: [
      { key: 'date', label: 'Date', format: 'date', sortable: true },
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'invoice_number', label: 'Invoice #', format: 'text', sortable: true },
      { key: 'method', label: 'Method', format: 'text', sortable: true },
      { key: 'amount', label: 'Amount', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
    ],
    showTotals: true,
  },

  // ─── Operations ────────────────────────────────────────────
  {
    slug: 'job-profitability',
    name: 'Job Profitability',
    description: 'Revenue vs cost per job to see margin',
    category: 'operations',
    icon: 'Hammer',
    availableFilters: ['date_range', 'job_id', 'project_id', 'status'],
    columns: [
      { key: 'job_title', label: 'Job', format: 'text', sortable: true },
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
      { key: 'revenue', label: 'Revenue', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'cost', label: 'Cost', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'profit', label: 'Profit', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'margin', label: 'Margin', format: 'percent', sortable: true, align: 'right' },
    ],
    showTotals: true,
  },
  {
    slug: 'project-profitability',
    name: 'Project Profitability',
    description: 'Budgeted vs actual costs per project',
    category: 'operations',
    icon: 'FolderKanban',
    availableFilters: ['date_range', 'project_id', 'status', 'customer_id'],
    columns: [
      { key: 'project_name', label: 'Project', format: 'text', sortable: true },
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
      { key: 'budget', label: 'Budget', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'actual_cost', label: 'Actual Cost', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'invoiced', label: 'Invoiced', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'variance', label: 'Variance', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },
  {
    slug: 'estimate-conversion',
    name: 'Estimate Conversion',
    description: 'Track estimate win rates and conversion to invoices',
    category: 'operations',
    icon: 'Target',
    availableFilters: ['date_range', 'customer_id'],
    columns: [
      { key: 'estimate_number', label: 'Estimate #', format: 'text', sortable: true },
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'date', label: 'Date', format: 'date', sortable: true },
      { key: 'total', label: 'Total', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
      { key: 'converted', label: 'Converted', format: 'text' },
    ],
    showTotals: true,
  },
  {
    slug: 'invoice-status',
    name: 'Invoice Status',
    description: 'All invoices with status, amounts paid and outstanding',
    category: 'operations',
    icon: 'FileCheck',
    availableFilters: ['date_range', 'customer_id', 'status'],
    columns: [
      { key: 'invoice_number', label: 'Invoice #', format: 'text', sortable: true },
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'issue_date', label: 'Issue Date', format: 'date', sortable: true },
      { key: 'due_date', label: 'Due Date', format: 'date', sortable: true },
      { key: 'total', label: 'Total', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'amount_paid', label: 'Paid', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'amount_due', label: 'Due', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
    ],
    showTotals: true,
  },
  {
    slug: 'customer-revenue',
    name: 'Customer Revenue',
    description: 'Total revenue per customer with job counts',
    category: 'operations',
    icon: 'Users',
    availableFilters: ['date_range'],
    columns: [
      { key: 'customer', label: 'Customer', format: 'text', sortable: true },
      { key: 'total_revenue', label: 'Total Revenue', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'total_invoiced', label: 'Total Invoiced', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'outstanding', label: 'Outstanding', format: 'currency', sortable: true, align: 'right', showTotal: true },
      { key: 'job_count', label: 'Jobs', format: 'number', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },

  // ─── Labor ─────────────────────────────────────────────────
  {
    slug: 'time-labor',
    name: 'Time & Labor',
    description: 'Hours worked by team member with labor costs',
    category: 'labor',
    icon: 'Clock',
    availableFilters: ['date_range', 'project_id', 'job_id'],
    columns: [
      { key: 'team_member', label: 'Team Member', format: 'text', sortable: true },
      { key: 'date', label: 'Date', format: 'date', sortable: true },
      { key: 'job_title', label: 'Job', format: 'text', sortable: true },
      { key: 'hours', label: 'Hours', format: 'number', sortable: true, align: 'right', showTotal: true },
      { key: 'rate', label: 'Rate', format: 'currency', align: 'right' },
      { key: 'labor_cost', label: 'Labor Cost', format: 'currency', sortable: true, align: 'right', showTotal: true },
    ],
    showTotals: true,
  },
  {
    slug: 'equipment-utilization',
    name: 'Equipment Utilization',
    description: 'Equipment assignments and usage tracking',
    category: 'labor',
    icon: 'Wrench',
    availableFilters: ['date_range'],
    columns: [
      { key: 'equipment_name', label: 'Equipment', format: 'text', sortable: true },
      { key: 'assigned_to', label: 'Assigned To', format: 'text', sortable: true },
      { key: 'job_title', label: 'Job', format: 'text', sortable: true },
      { key: 'assigned_date', label: 'Assigned', format: 'date', sortable: true },
      { key: 'returned_date', label: 'Returned', format: 'date', sortable: true },
      { key: 'days_out', label: 'Days Out', format: 'number', sortable: true, align: 'right', showTotal: true },
      { key: 'status', label: 'Status', format: 'status', sortable: true },
    ],
    showTotals: true,
  },
]

export function getTemplate(slug: string): ReportTemplate | undefined {
  return reportTemplates.find(t => t.slug === slug)
}

export function getTemplatesByCategory(category: string): ReportTemplate[] {
  return reportTemplates.filter(t => t.category === category)
}
